
jdbc:
  username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
  password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
  url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}